import * as _deepl from './deepl';
import * as _bing from './bing';
import * as _yandex from './yandex';
import * as _openai from './openai';
import * as _google from './google';
import * as _transmart from './transmart';
import * as _alibaba from './alibaba';
import * as _baidu from './baidu';
import * as _baidu_field from './baidu_field';
import * as _tencent from './tencent';
import * as _volcengine from './volcengine';
import * as _niutrans from './niutrans';
import * as _youdao from './youdao';
import * as _bing_dict from './bing_dict';
import * as _cambridge_dict from './cambridge_dict';
import * as _caiyun from './caiyun';
import * as _chatglm from './chatglm';
import * as _geminipro from './geminipro';
import * as _ollama from './ollama';
import * as _ecdict from './ecdict';
import * as _lingva from './lingva';
import * as _claude_code from './claude_code';
import * as _codex from './codex';
import type { TranslateService } from '../../types/service';

// `satisfies` checks each module against the contract in src/types/service.ts and emits nothing.
export const deepl = _deepl satisfies TranslateService;
export const bing = _bing satisfies TranslateService;
export const yandex = _yandex satisfies TranslateService;
export const openai = _openai satisfies TranslateService;
export const google = _google satisfies TranslateService;
export const transmart = _transmart satisfies TranslateService;
export const alibaba = _alibaba satisfies TranslateService;
export const baidu = _baidu satisfies TranslateService;
export const baidu_field = _baidu_field satisfies TranslateService;
export const tencent = _tencent satisfies TranslateService;
export const volcengine = _volcengine satisfies TranslateService;
export const niutrans = _niutrans satisfies TranslateService;
export const youdao = _youdao satisfies TranslateService;
export const bing_dict = _bing_dict satisfies TranslateService;
export const cambridge_dict = _cambridge_dict satisfies TranslateService;
export const caiyun = _caiyun satisfies TranslateService;
export const chatglm = _chatglm satisfies TranslateService;
export const geminipro = _geminipro satisfies TranslateService;
export const ollama = _ollama satisfies TranslateService;
export const ecdict = _ecdict satisfies TranslateService;
export const lingva = _lingva satisfies TranslateService;
export const claude_code = _claude_code satisfies TranslateService;
export const codex = _codex satisfies TranslateService;
